# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './mod7_2/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.matrix_size_sbox = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.matrix_size_sbox.setFont(font)
        self.matrix_size_sbox.setMinimum(2)
        self.matrix_size_sbox.setMaximum(10)
        self.matrix_size_sbox.setObjectName("matrix_size_sbox")
        self.horizontalLayout_2.addWidget(self.matrix_size_sbox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lambda_tab = QtWidgets.QTableView(self.centralwidget)
        self.lambda_tab.setObjectName("lambda_tab")
        self.lambda_tab.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.lambda_tab)
        self.calc_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.calc_btn.setFont(font)
        self.calc_btn.setObjectName("calc_btn")
        self.verticalLayout.addWidget(self.calc_btn)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.res_tab = QtWidgets.QTableView(self.centralwidget)
        self.res_tab.setObjectName("res_tab")
        self.res_tab.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.res_tab)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.exit_pbtn = QtWidgets.QMenu(self.menubar)
        self.exit_pbtn.setObjectName("exit_pbtn")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.exit_pbtn.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Матрица интенсивности"))
        self.label_3.setText(_translate("MainWindow", "Размер:"))
        self.calc_btn.setText(_translate("MainWindow", "Вычислить"))
        self.label_4.setText(_translate("MainWindow", "Результат"))
        self.exit_pbtn.setTitle(_translate("MainWindow", "Выход"))
